name: Validate Develop PR

on:
  push:
    branches:
      - develop

permissions:
  pull-requests: write
  contents: write

jobs:
  checkout-develop:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

  create-pull-request:
    runs-on: ubuntu-latest
    needs: checkout-develop
    
    steps:

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge develop into main'
          branch: 'auto-pr-develop-to-main'
          title: 'Merge develop into main'
          body: 'This PR merges changes from develop into main'
          base: 'main'